---
# tasks file for apache
- name: install
  yum:
    name:
    - httpd
    - mod_ssl
    state: present

- name: deploy config
  template:
    src: "{{ item }}"
    dest: /etc/httpd/conf.d/
  notify: restart httpd
  loop:
  - ssl_redirect.conf.inc

- name: set mpm
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm.conf
    regex: "^LoadModule mpm_prefork_module modules/mod_mpm_prefork.so"
    line: LoadModule mpm_event_module modules/mod_mpm_event.so
    state: present
  notify: restart httpd

- name: open firewall
  firewalld:
    service: "{{ item }}"
    immediate: yes
    permanent: yes
    state: enabled
  loop:
    - http
    - https
  when: use_firewalld

- name: configure logrotate
  copy:
    src: logrotate_httpd.conf
    dest: /etc/logrotate.d/httpd

- name: start httpd
  service:
    name: httpd
    enabled: yes
    state: started

- block:
  - name: install mod_ssl
    yum:
      name:
      - mod_ssl
      - openssl
      state: present

  - name: configure ssl
    lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regex: "{{ item.re }}"
      line: "{{ item.line }}"
      state: present
    loop:
    - { re: "^SSLProtocol", line: "SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1" }
    #- { re: "^SSLCertificateFile /etc/pki/tls/certs/localhost.crt", line: "SSLCertificateFile  {{ http_ssl_certificate_file}}" }
    #- { re: "^SSLCertificateKeyFile /etc/pki/tls/private/localhost.key", line: "SSLCertificateKeyFile  {{ http_ssl_certificate_key }}" }
  when: httpd_have_ssl


